spring:
  datasource:
    #driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/main
    username: root
    password: password
  jpa:
    show-sql: true
    #database-platform: org.hibernate.dialect.MySQL5
    database: mysql

server:
  port: 8090
